spring:
  application:
    name: hystrix-consumer2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: hystrix-consumer2

server:
  port: 8506

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream